#!/bin/bash

apt=/usr/bin/apt-get

# We do each operation twice in order to minimize risks of
# temporary errors (I get lots of 505 here)

$apt update
$apt update
# Autoclean is disabled because when one gets Hashsum mismatch there
# is no more list from the failed server and all downloaded packages
# vanish. (See bug #624122)
# $apt autoclean
$apt -y --force-yes --download-only dist-upgrade
$apt -y --force-yes --download-only install
$apt -y --force-yes --download-only dist-upgrade
$apt -y --force-yes --download-only install
